# Generated by Django 4.1.3 on 2022-11-27 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumed_quantity', models.CharField(max_length=64)),
                ('cost', models.CharField(max_length=64)),
                ('date', models.CharField(max_length=64)),
                ('instance_id', models.CharField(max_length=64)),
                ('meter_category', models.CharField(max_length=64)),
                ('resource_group', models.CharField(max_length=64)),
                ('resource_location', models.CharField(max_length=64)),
                ('tags_app_name', models.CharField(max_length=64)),
                ('tags_environment', models.CharField(max_length=64)),
                ('tags_business_unit', models.CharField(max_length=64)),
                ('unit_of_measure', models.CharField(max_length=64)),
                ('location', models.CharField(max_length=64)),
                ('service_name', models.CharField(max_length=64)),
            ],
        ),
    ]
