# Generated by Django 4.1.3 on 2022-11-29 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='slug',
            field=models.CharField(default=0, max_length=64),
            preserve_default=False,
        ),
    ]
