# Generated by Django 4.1.3 on 2022-11-29 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0002_data_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='slug',
        ),
    ]
